project_name: gh-spec-verify

before:
  hooks:
    - go mod tidy

builds:
  - id: gh-spec-verify
    main: ./cmd/gh-spec-verify
    binary: gh-spec-verify
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: k-totani
    name: gh-spec-verify
  prerelease: auto
